apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: machine-api
resources:
  - ../base
  # include if using secrets from vault
  # - secrets.yaml
replicas:
  - name: machine-api
    count: 2
configMapGenerator:
  - name: env-config
    literals:
      - SENTRY_ENV=PREVIEW
