on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-clippy.yml
      - "rust-toolchain.toml"
      - "openapi/*.json"
  pull_request:
    paths:
      - "**.rs"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-clippy.yml
      - "rust-toolchain.toml"
      - "openapi/*.json"
name: cargo clippy
jobs:
  cargoclippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libudev-dev
        shell: bash
      - name: Run clippy
        run: cargo clippy --workspace --tests -- -D warnings
      - name: Cargo check --release
        run: cargo check --release
